### ISSUE TITLE
Bookmap crashes if trading anything other than BTC

### ISSUE THREAD

**Issue by muffinrecon** [BookmapAPI/bitmex-adapter#9]
Error here when trading anything other than btc on bitmex.
```
Full report content:

com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected a long but was 1.3115545542323785 at line 1 column 1051 path $[0].foreignNotional
	at com.google.gson.internal.bind.TypeAdapters$8.read(TypeAdapters.java:265)
	at com.google.gson.internal.bind.TypeAdapters$8.read(TypeAdapters.java:255)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:117)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:217)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:814)
	at com.google.gson.Gson.fromJson(Gson.java:779)
	at com.google.gson.Gson.fromJson(Gson.java:728)
	at com.google.gson.Gson.fromJson(Gson.java:700)
	at com.bookmap.plugins.layer0.bitmex.adapter.JsonParser.getArrayFromJson(JsonParser.java:26)
	at com.bookmap.plugins.layer0.bitmex.adapter.BmConnector.reportHistoricalExecutions(BmConnector.java:399)
	at com.bookmap.plugins.layer0.bitmex.adapter.BmConnector.wsConnect(BmConnector.java:168)
	at com.bookmap.plugins.layer0.bitmex.adapter.BmConnector.run(BmConnector.java:449)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: Expected a long but was 1.3115545542323785 at line 1 column 1051 path $[0].foreignNotional
	at com.google.gson.stream.JsonReader.nextLong(JsonReader.java:980)
	at com.google.gson.internal.bind.TypeAdapters$8.read(TypeAdapters.java:263)
	... 14 more

```

**Comment by AndryRadchenko** [comment]
Fixed in October 2018
